### ISSUE TITLE
Put it into the git ignore

### ISSUE THREAD

**Issue by filip326** [Mickhat/FloBot#79]
simply because it's not in the gitignore

_Originally posted by @Barsch2006 in https://github.com/Mickhat/FloBot/issues/78#issuecomment-1889843205_

**Comment by Barsch2006** [comment]
we should check, if its not easier with the package-lock 'cause `npm ci`in the action

**Comment by Barsch2006** [comment]
@filip326 https://chat.openai.com/share/91b580c1-a748-4746-838a-590e3b1d3e43

**Comment by Barsch2006** [comment]
I talked shit. It has a proper reason to exist on github

**Comment by Barsch2006** [comment]
https://github.com/Mickhat/FloBot/blob/master/Dockerfile

take a closer look in the actions, the package.json and the Dockerfile ;)

**Comment by filip326** [comment]
We should check if its possible to use the yarn.lock inside the github actions

**Comment by filip326** [comment]
@oglimmer you've got most experince with gh actions and this stuff

**Comment by Barsch2006** [comment]
its completly possible. its just a question, if its required after a year of development..

**Comment by filip326** [comment]
> and since the actions've used npm since they exist, I don't get why you used yarn the whole time ;)

Because @Mickhat asked me to

**Comment by Barsch2006** [comment]
aha (oder auf Deutsch: immer schön die Schuld auf andere schieben ;))

**Comment by filip326** [comment]
![image](https://github.com/Mickhat/FloBot/assets/89743412/bb4b2996-5428-4a02-9377-d2238f5a730b)
(auf Deutsch: Beweis)

**Comment by Barsch2006** [comment]
ja ok

**Comment by Mickhat** [comment]
habbit i guess

**Comment by chfuchte** [comment]
> habbit i guess

damit wäre wohl alles gesagt
